name: Deploy to Staging

on:
  push:
    branches:
      - staging

permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '8.0'

      - name: Build Application
        run: |
          dotnet restore
          dotnet publish -c Release -o ./out
          ls -la ./out

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-app
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dotnet-app
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: List files in the directory
        run: |
          pwd
          ls -la ../
          ls -la
      - name: Deploy to Azure
        run: |
          az webapp deploy --resource-group delaey-rg-staging-westeurope-01 \
                          --name delaey-webapp-staging-westeurope-01 \
                          --src-path ./minimal-api-example-sad